- projects/client-side-events/datasets/Viewer_Events/tables/eventsYYYYMMDD
- projects/client-side-events/datasets/Viewer_Events/views/ViewerActivity.bq
> Add Viewer_Events

- projects/client-side-events/datasets/Native_Events/tables/eventsYYYYMMDD
- projects/client-side-events/datasets/Native_Events/views/ConsistentlyUngracefulUnsettledDisplays.bq
- projects/client-side-events/datasets/Native_Events/views/MultipleUnreliableV3StartsPlayerCount.bq
- projects/client-side-events/datasets/Native_Events/views/PlayerReliabilityStats.bq
- projects/client-side-events/datasets/Native_Events/views/ReliabilityOverYear.bq
> Add Native_Events dataset

- projects/rvaserver2/datasets/appengine_logs/views/DisplayCosts.bq
@tejohnso this table was missed in the previous PR
> Add rvaserver2:appengine_logs.DisplayCosts

- projects/client-side-events/datasets/Installer_Events/views/DisplayCountByInstallerType.bq
@tejohnso @stulees please review.cheers
> Updated view with latest from bq

- projects/client-side-events/datasets/Widget_Events/views/ImageDailyReliability.bq
- projects/client-side-events/datasets/Widget_Events/views/RssDailyReliability.bq
- projects/client-side-events/datasets/Widget_Events/views/SpreadsheetDailyReliability.bq
- projects/client-side-events/datasets/Widget_Events/views/TextDailyReliability.bq
- projects/client-side-events/datasets/Widget_Events/views/VideoDailyReliability.bq
@stulees @tejohnso I had to increase the number of the days so it can group previous day dates that appears on events from a certain day. Please review. cheers
> Updated queries to fix issue with duplicate dates

- projects/client-side-events/datasets/Aggregate_Tables/DisplayInfo
- projects/client-side-events/datasets/Installer_Events/views/DisplayInfo.bq
@tejohnso please review. cheers
@alexey-rise FYI. cheers
> Added displayInfo query and aggregate table

- projects/client-side-events/datasets/Installer_Events/views/DisplayInfo.bq
@tejohnso @stulees please review. cheers
> Changed query to fix the query for getting use channel displays

- projects/client-side-events/datasets/Installer_Events/views/ModuleUpgradeStats.bq
Requires additional Installer log, proposed in https://github.com/Rise-Vision/rise-launcher-electron/pull/674
> Add Module Upgrade Stats query

- projects/client-side-events/datasets/Module_Events/licensing_reliability.bq
> Add licensing reliability view

- projects/client-side-events/datasets/Component_Events/views/TwitterDailyReliability.bq
- projects/client-side-events/datasets/Component_Events/views/TwitterDailyUsage.bq
- projects/client-side-events/datasets/Component_Events/views/TwitterUsageByMonth.bq
- projects/client-side-events/datasets/Component_Events/views/TwitterUsageUnlicensed.bq
Added existing views, updated reliability and added unlicensed display usage
@Rise-Vision/content please review
> Twitter views

- projects/client-side-events/datasets/Component_Events/views/TwitterDailyReliability.bq
@Rise-Vision/content please review
> Cast date to string and query for correct error logs

- projects/client-side-events/datasets/Installer_Events/views/PlayerModuleStats.bq
@Rise-Vision/delivery please review
> Added certificate error to player reliability

- projects/client-side-events/datasets/Widget_Events/views/ImageVideoReliability.bq
- Reports last 7 days of 
- Image RLS Single File
- Image RLS Folder
- Image w/ Rise Cache
- Video RLS Single File
- Video RLS Folder
- Video w/ Rise Cache
> Consolidating Image/Video reliability to one View

- projects/client-side-events/datasets/Widget_Events/views/CoreWidgetsReliability.bq
- Reports last 7 days of 
- Calendar
- RSS
- Spreadsheet
- Text
- Twitter
- Excludes Image/Video as they have a separate consolidated view (RLS & RC)
> Adding core widgets reliability view, excludes Image/Video

- projects/client-side-events/datasets/Aggregate_Tables/DisplayActivation.bq
- Remove displays from test companies and Rise Vision company
> Display Activation query improvements

- projects/client-side-events/datasets/Widget_Events/queries/MediaErrSrcNotSupported.bq
Simple query for getting the display ids and failing files related to this error.
> add query for MEDIA_ERR_SRC_NOT_SUPPORTED errors

- projects/client-side-events/datasets/Installer_Events/views/DisplayCountByInstallerType.bq
@Rise-Vision/delivery please review
> ChromeOS count

- projects/client-side-events/datasets/Module_Events/daily_monthly_active_company_ratio.bq
This is the KPI definition:
https://docs.google.com/document/d/1n4O6MVWxNGRE1nDHf07HSXsiuciyysUxnqc89mtEb4c/edit#heading=h.10mkdi205gve
This query is heavy because it gathers data for a complete month.
> add daily / monthly active company ratio query

- projects/client-side-events/datasets/Module_Events/viewer_crash.bq
Win7 is not consistent
@Rise-Vision/delivery please review
> Update viewer reliability.

- projects/client-side-events/datasets/Uptime_Events/views/AverageUptimePctIgnoringNetworkConnectivity.bq
- projects/client-side-events/datasets/Uptime_Events/views/DisplayUptimePctFourDaysAgoToYesterdayIgnoringNetworkConnectivity.bq
This gets us to 99% :1st_place_medal:
> Add views which ignore network connectivity

- projects/client-side-events/datasets/Component_Events/views/OAuthTokenProviderStats.bq
I was printing the current day instead of the day before, this fixes it.
> use day before instead of today

- .gitignore
- projects/Rise_Stats/datasets/customerData/views/companySnapshot.bq
- projects/Rise_Stats/datasets/customerData/views/subscriptionSnapshot.bq
- projects/Rise_Stats/datasets/customerData/views/userSnapshot.bq
@tejohnso @andrecardoso please review.
> Added customerData views

- projects/Rise_Stats/datasets/customerData/views/companyChanges.bq
- projects/Rise_Stats/datasets/customerData/views/subscriptionChanges.bq
- projects/Rise_Stats/datasets/customerData/views/userChanges.bq
- projects/Rise_Stats/datasets/customerData/views/userSnapshot.bq
@tejohnso @andrecardoso please review.
> added xxxChanged views, fixed userSnapshot view

- projects/Rise_Stats/datasets/customerData/views/companySnapshot.bq
@andrecardoso @tejohnso please review.
> Correct industry field

- projects/client-side-events/datasets/Aggregate_Tables/CompanyDisplaysWithMRR.bq
Makes it easier to see displays platform per company MRR
> Add CompanyDisplaysWithMRR view

- projects/client-side-events/datasets/Player_Data/K12RecommendedPlayerPct.bq
- projects/client-side-events/datasets/Player_Data/K12RecommendedPlayerPctHistory.bq
> Add K12RecommendedPlayerPct

- projects/client-side-events/datasets/Player_Data/K12RecommendedPlayerPct.bq
- projects/client-side-events/datasets/Player_Data/RecentlyRunningDisplays.bq
> Only consider recently running K12 displays

- projects/Rise_Stats/datasets/coreData/views/K12Displays.bq
- projects/Rise_Stats/datasets/coreData/views/displaysWithWhiteScreenDueToPlaceholderSchedule.bq
- projects/Rise_Stats/datasets/coreData/views/displaysWithWhiteScreenDueToWidgetSchedule.bq
- projects/Rise_Stats/datasets/coreData/views/presentationsOnDisplays.bq
- projects/Rise_Stats/datasets/coreData/views/presentationsWithContentGapsDueToPlaceholderSchedule.bq
- projects/Rise_Stats/datasets/coreData/views/presentationsWithContentGapsDueToWidgetSchedule.bq
- projects/Rise_Stats/datasets/coreData/views/presentationsWithNoContentDueToPlaceholderSchedule.bq
- projects/Rise_Stats/datasets/coreData/views/presentationsWithNoContentDueToWidgetSchedule.bq
- projects/client-side-events/datasets/Uptime_Events/views/K12AverageUptimePct.bq
- projects/client-side-events/datasets/Uptime_Events/views/K12DowntimeDueToMSDisconnectionWithIssueDetected.bq
- projects/client-side-events/datasets/Uptime_Events/views/K12DowntimeDueToWhiteScreenCausedByGapsInWidgetSchedule.bq
@tejohnso @andrecardoso please review.
> K-12 Uptime and related queries

- projects/client-side-events/datasets/Component_Uptime_Events/tables/events.sql
- projects/client-side-events/datasets/Template_Uptime_Events/tables/events.sql
@alex-deaconu Tables were added to BQ. Please review. Thanks
> Adding Template and Component uptime tables

- projects/client-side-events/datasets/Display_Events/ComponentErrorsAndWarnings.bq
- projects/client-side-events/datasets/Display_Events/ComponentStats.bq
> exclude test companies in reliability and errors

- projects/client-side-events/datasets/Component_Uptime_Events/views/DailyUptime.bq
- projects/client-side-events/datasets/Component_Uptime_Events/views/DailyUptimePerComponent.bq
- projects/client-side-events/datasets/Template_Uptime_Events/views/DailyUptime.bq
- projects/client-side-events/datasets/Template_Uptime_Events/views/DailyUptimePerTemplate.bq
Initial set of queries to report Templates and Components uptime.
@alex-deaconu Please review.
> Content Uptime Queries

- projects/client-side-events/datasets/Installer_Events/views/DisplayCountByInstallerType.bq
> Ensure previous day data in display count

- projects/Rise_Stats/datasets/customerData/views/companySnapshot.bq
- projects/Rise_Stats/datasets/customerData/views/userSnapshot.bq
> Accounted for deleted users and companies in snapshot queries

- projects/Rise_Stats/datasets/customerData/views/userSnapshot.bq
> accounted for user that were deleted and re-created

- projects/client-side-events/datasets/Display_Events/ComponentReliabilityStable.bq
> Add rise-time-date stable reliability tracking

- projects/client-side-events/datasets/Apps_Events/views/AppsFunnelDaily.bq
- projects/client-side-events/datasets/Apps_Events/views/AppsFunnelWeekly.bq
- projects/client-side-events/datasets/Apps_Events/views/AppsFunnelWeeklyNoSubcompanies.bq
- projects/client-side-events/datasets/Apps_Events/views/CustomerJourneyAnalysisView.bq
- projects/client-side-events/datasets/Apps_Events/views/SignUpsDaily.bq
Handle both old and new events on Apps_Events views
@alex-deaconu Please review. Thanks!
> Update Apps_Events to handle new taxonomy

- projects/client-side-events/datasets/Widget_Events/queries/SharedScheduleUptime.bq
Added Shared Schedule Uptime query
> Added Shared Schedule Uptime query

- projects/endpoint-event-logs/datasets/logs/DailyErrorsSummary.sql
Added daily errors summary query
> Added daily errors summary query

- projects/endpoint-event-logs/datasets/logs/DailyErrorsSummary.sql
Fixed company lookup for shared schedules
> Fixed company lookup for shared schedules

- projects/endpoint-event-logs/datasets/logs/DailyErrorsSummary.sql
- projects/endpoint-event-logs/datasets/logs/DailyUsageSummary.sql
Added daily usage summary query and removed deletion checks from error summary query
> Added daily usage summary query

- projects/endpoint-event-logs/datasets/logs/DailyCostSummary.sql
> Added daily cost summary scheduled query

- projects/endpoint-event-logs/datasets/logs/DailyUptimeSummary.sql
> Added daily uptime summary scheduled query

- projects/endpoint-event-logs/datasets/logs/DailyUptimeSummary.sql
> Removed duplicates from the list of intervals

- projects/endpoint-event-logs/datasets/views/activeDisplays.sql
- projects/endpoint-event-logs/datasets/views/templateUsageByDisplays.sql
> Added commonly-used queries as views

- projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
- projects/endpoint-event-logs/datasets/logs/dailyErrorsSummary.sql
- projects/endpoint-event-logs/datasets/logs/dailyUptimeSummary.sql
- projects/endpoint-event-logs/datasets/logs/dailyUsageSummary.sql
- projects/rise-core-log/datasets/coreData/licensedDisplays.sql
> Removed invalid licenseStatus reference from daily error summary view

- projects/endpoint-event-logs/datasets/views/downtimeCauses.sql
- projects/endpoint-event-logs/datasets/views/endpointUptime.sql
> Convenience views

- projects/endpoint-event-logs/datasets/logs/dailyUptimeSummary.sql
Only `eventApp=='Viewer'` was included into uptime. This change adds the rest of the eventApps.
> Corrected eventApp/eventAppVersion lookup for EventAppUptime calculation

- projects/endpoint-event-logs/datasets/logs/cleanUpEventApp.sql
Function that (somewhat) cleans up legacy eventApp values.
> EventApp clean up function for use in queries and views

- projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
- projects/endpoint-event-logs/datasets/logs/dailyErrorsSummary.sql
- projects/endpoint-event-logs/datasets/logs/dailyUptimeSummary.sql
- projects/endpoint-event-logs/datasets/logs/dailyUsageSummary.sql
> Added eventApp cleanup to summary queries

- projects/endpoint-event-logs/datasets/logs/cleanUpEventApp.sql
Revised eventApp clean up to extract the Core GUID instead of the name
> Revised eventApp clean up to extract the Core GUID instead of the name

- projects/endpoint-event-logs/datasets/views/templateUsageByDisplays.sql
> Changed the meaning of template Id as per Alan's feedback

- projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
Eliminated duplicate rows, incorrect joins and and precision errors
> Eliminated duplicate rows, incorrect joins and and precision errors

- projects/endpoint-event-logs/datasets/views/dailyCostLast60Days.sql
- projects/endpoint-event-logs/datasets/views/endpointInfrastructureCostsLast60Days.sql
Added views that introduce infrastructure costs into endpoint costs
> Added views that introduce infrastructure costs into endpoint costs

- projects/endpoint-event-logs/datasets/logs/dailyUptimeSummary.sql
Revised uptime summary query to match the new errorDefinitions structure
> Revised uptime summary query to match the new errorDefinitions structure

- projects/endpoint-event-logs/datasets/views/dailyCostLast60Days.sql
Excluded InApp endpoints from last 60 days cost calculation as per Alan's request.
> Excluded InApp endpoints from last 60 days cost calculation
