Rise-Vision/bigquery-queries

projects/client-side-events/datasets/Installer_Events/views/DisplayCountByInstallerType.bq, projects/client-side-events/datasets/Installer_Events/views/NewInstallationStats.bq, projects/client-side-events/datasets/Installer_Events/views/UpgradeStats.bq, projects/client-side-events/datasets/Native_Events/views/MultipleUnreliableV3StartsPlayerCount.bq, projects/client-side-events/datasets/Native_Events/views/PlayerReliabilityStats.bq
@tejohnso @fjvallarino ready for review.
There are some changes that might seem weird and unnecessary. Most of those changes were made to work around BigQuery quirks.
This needs to go in after https://github.com/Rise-Vision/client-side-events/pull/18
=> Do not recalculate past data; use cache instead

projects/client-side-events/datasets/Native_Events/views/ConsistentlyUngracefulUnsettledDisplays.bq
@tejohnso as discussed, instead of querying range [-9, 0], we now query range [-10, -1].
In effect, we're including the same number of days, but there are
no fluctuations in the results since we don't include current day,
whose data can change between queries.
=> ConsistentlyUngracefulUnsettledDisplays excludes current day

projects/client-side-events/datasets/Native_Events/views/ConsistentlyUngracefulUnsettledDisplays.bq, projects/client-side-events/datasets/Native_Events/views/MultipleUnreliableV3StartsPlayerCount.bq
@ahmedalsudani @fjvallarino please review for inclusion of "watchdog restart" events in unreliable display count.
=> Include installer watchdog events in player metrics

projects/client-side-events/datasets/Native_Events/views/PlayerReliabilityStats.bq
Adds a column for starts that only consider players that user Java
Player.  This is to be used for the denominator in the reliability incl
v2 metric which expects Java Player's graceful shutdown flag.
@fjvallarino please review
=> Fix java player stats for reliability metric incl v2

projects/client-side-events/datasets/Installer_Events/views/DisplayCountByInstallerType.bq
@tejohnso 
This makes it possible to include dates when not all of our players
reported data
=> Use left joins in DisplayCountByInstallerType

projects/client-side-events/datasets/Native_Events/views/PlayerReliabilityStats.bq
@tejohnso Here's the fix for the Player Reliability Stats chart.
If you want a demo, take a look at the chart at the bottom of our dashboard and at the table `Aggregate_Tables.DeleteMePlayerReliabilityStats`
This allows us to calculate reliability without querying
DisplayCountByInstallerType (on the dashboard side).
Using the latter has been problematic because the date
range was recently extended past our reliabilty data,
which caused our chart to include dates on which we
lacked data.
=> Include player count in PlayerReliabilityStats

projects/client-side-events/datasets/Installer_Events/views/DisplayCountByInstallerType.bq, projects/client-side-events/datasets/Viewer_Events/views/APICallsFromV3.bq
Since v3 players with recent viewer versions no longer use the core api
call, we can't rely on accurate core counts for v3.
This removes the v3 player counts from the total count coming from core
logs and adds the Installer_Events count to get v3 total.
@fjvallarino please review
=> Don't use core logs for v3 counts

projects/rise-core-log/datasets/billingData/CostByDateAndProjectView.bq, projects/rise-core-log/datasets/billingData/ProjectCostColumnsByDateView.bq
Added viewer, viewer test, storage test, and core test to cost query.
Some previous changes weren't committed so the diff isn't accurate. For example, I didn't remove contentfiancial2, it was already absent from the query on BQ.
=> Update cost queries for kpi

projects/client-side-events/datasets/Installer_Events/views/ModuleUpgradeStats.bq, projects/client-side-events/datasets/Installer_Events/views/NewInstallationStats.bq
- To give us accurate stable Launcher (installer) reliability stats, the query should be based on latest stable version. I will have to update the query every time we release a new installer to stable
- Can't use MAX as we will continuously build staged installers with a version higher than stable
=> Installer and upgrade reliability based on latest installer version

projects/client-side-events/datasets/Module_Events/module_versions.bq
If we add a module and we want to dynamically query its version from the GCS manifest, we'll have to add it to this view. I couldn't find a better way to get at the data. Tried multiple uses of `unnest` to no avail.
=> Add view for module versions

projects/client-side-events/datasets/Rise_Cache_V2/views/CacheV2DailyReliability.bq, projects/client-side-events/datasets/Widget_Events/views/ImageDailyReliability.bq, projects/client-side-events/datasets/Widget_Events/views/RssDailyReliability.bq, projects/client-side-events/datasets/Widget_Events/views/SpreadsheetDailyReliability.bq, projects/client-side-events/datasets/Widget_Events/views/TextDailyReliability.bq
- for image widget queries changed references from `play` event to `configuration` event as per `widget-image` [#141](https://github.com/Rise-Vision/widget-image/pull/141)
- fixed typo `client-side-EVENTS` --> `client-side-events`
=> Fix/change references from 'play' to 'configuration' on image reliability

projects/client-side-events/datasets/Widget_Events/views/ImageRLSStats.bq, projects/client-side-events/datasets/Widget_Events/views/VideoRLSStats.bq
- Written initially to filter for only single storage file (through RLS single file rollout)
- Conditions specify the stats to be from displays that are configured for storage single file and use RLS only
=> Adding Image and Video use RLS views

projects/client-side-events/datasets/Widget_Events/views/ImageRLSStats.bq, projects/client-side-events/datasets/Widget_Events/views/VideoRLSStats.bq
- Filter out beta displays for Image & Video RLS single file stats. Leveraging the `beta_` prefix that Installer adds to the `installer_version`. 
@jungeunyoon @santiagonoguez This was the most straight forward and accurate way I've seen to filter out beta displays, some reasoning is:
- If I chose to use the latest module version of Launcher or Player, it couples the Widgets reliability to Player releases which would skew the stats. 
- If I chose to use the player configuration table `player_name` field which gets _(Beta)_  prefixed to the name, there is a chance within the 3 day range specified that the display switched from Stable to Beta or vice versa. A likely rare scenario, but it is possible and might skew stats. 
@Rise-Vision/delivery FYI
=> Filter out beta displays for RLS single file stats

projects/client-side-events/datasets/Module_Events/watchdog_reliability.bq
We changed it in BigQuery on Jun-5 but I forgot to change it here.
=> Change watchdog reliability query to catch errors that were not being reported

projects/client-side-events/datasets/Widget_Events/views/ImageDailyReliability.bq, projects/client-side-events/datasets/Widget_Events/views/VideoDailyReliability.bq
- We are tracking Image/Video using RLS reliability separately, so these original Image/Video reliability queries will eventually become obsolete. For now, exclude displays using RLS so reliability is solely based on using Rise Cache
=> Ensure no displays using RLS are included

projects/client-side-events/datasets/Widget_Events/views/ImageRLSStats.bq, projects/client-side-events/datasets/Widget_Events/views/VideoDailyReliability.bq, projects/client-side-events/datasets/Widget_Events/views/VideoRLSStats.bq
- Remove accepting _unauthorized_ and _file does not exist_ as errors as they will be now logged as a `warning`
- Improve Video (using RC) reliability to exclude player error from RLS instance by filtering out `risemedialibrary-%` in file_url
- Remove specificity of event_details for a player error in Video RLS stats, unnecessary
=> Improving specificity in Image/Video RLS and Video reliability stats

projects/client-side-events/datasets/Widget_Events/views/VideoDailyReliability.bq
- Query was starting to error with "Too many tables and views for query: Max: 1000" due to querying all Installer_Events.events tables. Fixing to just take range of last 10 days of Installer_Events.events tables
=> Fix VideoDailyReliability view

projects/client-side-events/datasets/Widget_Events/views/ImageFolderRLSStats.bq, projects/client-side-events/datasets/Widget_Events/views/VideoFolderRLSStats.bq
- Written separate from single file to track the configurations separately
- Conditions specify the stats to be from stable displays that are configured for storage folder and use RLS only
=> Adding Image and Video use RLS for Folder views

projects/client-side-events/datasets/Widget_Events/views/RssDailyReliability.bq
- Clean up some formatting
- Basing usage on "configuration" event and not "play" as "play" has been removed
- Reducing table range down to 3 days, 10 is excessive
Will apply the changes on Big Query UI after https://github.com/Rise-Vision/widget-rss/pull/117 is merged.
=> Revise RSS reliability to use new "configuration" event

projects/client-side-events/datasets/Widget_Events/views/TextDailyReliability.bq
- Clean up some formatting
- Basing usage on "configuration" event and not "play" as "play" has been removed
- Reducing table range down to 3 days, 10 is excessive
Will apply the changes on Big Query UI after https://github.com/Rise-Vision/widget-text/pull/129 gets merged.
=> Revise text reliability to use new "configuration" event

projects/client-side-events/datasets/Widget_Events/views/SpreadsheetDailyReliability.bq
- Clean up some formatting
- Basing usage on "configuration" event and not "play" as "play" has been removed
- Reducing table range down to 3 days, 10 is excessive
Will apply the changes on Big Query UI after https://github.com/Rise-Vision/widget-google-spreadsheet/pull/303 is merged.
=> Revise spreadsheet reliability to use new "configuration" event

projects/client-side-events/datasets/Module_Events/licensing_reliability.bq
Removing deleted displays from licensing queries. Deleted displays don't get updates to display.json and will report errors.
=> Licensing reliability counting deleted displays

projects/client-side-events/datasets/Widget_Events/views/ImageFolderRLSStats.bq, projects/client-side-events/datasets/Widget_Events/views/ImageRLSStats.bq, projects/client-side-events/datasets/Widget_Events/views/VideoFolderRLSStats.bq, projects/client-side-events/datasets/Widget_Events/views/VideoRLSStats.bq
- “configuration” column already filters events pertaining to RC
- These conditionals have been filtering some errors needed to be tracked
=> Remove Image/Video RLS error conditionals

projects/client-side-events/datasets/Widget_Events/queries/ImageNonRLS_TopErrorsByDay.bq, projects/client-side-events/datasets/Widget_Events/queries/VideoNonRLS_TopErrorsByDay.bq, projects/client-side-events/datasets/Widget_Events/views/ImageVideoReliability.bq
- Use new non RLS aggregate tables for ImageVideoReliability query
- Add top errors by day queries for Image and Video non RLS
=> Revise ImageVideoReliability view and add top errors for non RLS

projects/client-side-events/datasets/Widget_Events/queries/ImageNonRLS_TopErrorsByDay.bq, projects/client-side-events/datasets/Widget_Events/queries/VideoNonRLS_TopErrorsByDay.bq, projects/client-side-events/datasets/Widget_Events/views/ImageNonRLSStats.bq, projects/client-side-events/datasets/Widget_Events/views/VideoNonRLSStats.bq
- `image load error` should be included to impact reliability
- `rise cache not running` has not been included for some time but should be as it helps to indicate displays having a problem
=> Account for missing error conditionals for Image/Video Non RLS reliability

projects/client-side-events/datasets/Widget_Events/queries/ImageLoadErrors.bq
- Filtering out “svg” format temporarily as the fix for SVG files has yet to be picked up by all displays
=> List unique files and display ids for image load error

projects/client-side-events/datasets/Widget_Events/queries/CalendarTopErrorsByDay.bq, projects/client-side-events/datasets/Widget_Events/queries/ImageFolderRLS_TopErrorsByDay.bq, projects/client-side-events/datasets/Widget_Events/queries/ImageSingleRLS_TopErrorsByDay.bq, projects/client-side-events/datasets/Widget_Events/queries/RssTopErrorsByDay.bq, projects/client-side-events/datasets/Widget_Events/queries/SpreadsheetTopErrorsByDay.bq, projects/client-side-events/datasets/Widget_Events/queries/TextTopErrorsByDay.bq, projects/client-side-events/datasets/Widget_Events/queries/VideoFolderRLS_TopErrorsByDay.bq, projects/client-side-events/datasets/Widget_Events/queries/VideoSingleRLS_TopErrorsByDay.bq, projects/client-side-events/datasets/Widget_Events/views/CalendarStats.bq, projects/client-side-events/datasets/Widget_Events/views/ImageFolderRLSStats.bq, projects/client-side-events/datasets/Widget_Events/views/ImageRLSStats.bq, projects/client-side-events/datasets/Widget_Events/views/RssDailyReliability.bq, projects/client-side-events/datasets/Widget_Events/views/SpreadsheetDailyReliability.bq, projects/client-side-events/datasets/Widget_Events/views/TextDailyReliability.bq, projects/client-side-events/datasets/Widget_Events/views/VideoFolderRLSStats.bq, projects/client-side-events/datasets/Widget_Events/views/VideoRLSStats.bq
- Measuring reliability of Content against all _non-beta_ Electron and Chrome OS displays
- Converted remaining Content reliability views from legacy to standard SQL
=> Include ChromeOS in Content reliability view/queries

projects/client-side-events/datasets/ChromeOS_Player_Events/views/reliability.bq
Using `ends_with` instead of `=` we'll be capturing displays during beta as well since their player_version is `beta_[version]`
Once in production this will still work, and beta displays won't be mixed into the results since they'll be on an older version.
=> Consider beta displays in reliability query

projects/client-side-events/datasets/Module_Events/content_displays_with_update.bq
KPI definition is this one:
https://docs.google.com/document/d/1n4O6MVWxNGRE1nDHf07HSXsiuciyysUxnqc89mtEb4c/edit#heading=h.b7vbjgqf881t
This is similar to previous PR:
https://github.com/Rise-Vision/bigquery-queries/pull/92
but counts by distinct display ID here:
https://github.com/Rise-Vision/bigquery-queries/compare/feature/content_displays_with_update?expand=1#diff-9a80ad5fe56d858c55621c704dedef6bR54
=> add displays with update query

projects/client-side-events/datasets/Module_Events/daily_monthly_active_company_ratio.bq
The definition for active display has changed from 'last 3 days' to 'latest day only', so the query has been changed to reflect that.
=> consider only last day for daily active displays

projects/client-side-events/datasets/Module_Events/daily_monthly_active_company_ratio.bq
The query is incorrectly showing the current day instead of the previous day.
=> show previous day instead of current day

projects/client-side-events/datasets/Uptime_Events/views/DisplayUptimePctFourDaysAgoToYesterday.bq, projects/client-side-events/datasets/Uptime_Events/views/DisplayUptimePctFourDaysAgoToYesterdayIgnoringNetworkConnectivity.bq
Noticed some future days showing up in the queries today.
=> Don't allow future days in uptime queries

projects/client-side-events/datasets/Display_Events/component_errors_and_warnings.bq
This query will get errors and warning counts for all content components ( not just image component ). I think this is very useful as the output can be very easily exported to a spreadsheet, and further filtered or copied there easily. Much easier than with Current Delivery's error counts.
See example: https://bigquery.cloud.google.com/results/client-side-events:US.bquijob_7cf08c5f_1671de469ca
Relability queries will be a separate PR.
=> count errors and warnings on all content components

projects/client-side-events/datasets/Display_Events/ComponentErrorsAndWarnings.bq, projects/client-side-events/datasets/Display_Events/ComponentStats.bq
The queries should be pointing to the production tables, not the test versions of them.
=> point to production table

projects/client-side-events/datasets/Component_Events/views/OAuthTokenProviderReliability.bq
An authentication error could be related to a user providing wrong credentials, and shouldn't affect content reliability. So I'm filtering out these type of errors.
=> filter out authentication errors

projects/client-side-events/datasets/Display_Events/ClientSideApplicationsTableCost.bq, projects/client-side-events/datasets/Display_Events/ClientSideApplicationsTableStats.bq
This is the proposal to track cost for streaming inserts on the Client Side Applications Table.
This calculates cost as defined here:
https://cloud.google.com/bigquery/pricing
Depending on the size of each record as described here:
https://stackoverflow.com/questions/40855461/how-to-calculate-bigquery-row-size
We would schedule the stats query to run daily and populate an aggregate table.
Then the cost query would give us the cost per component, and aggregating those we would get an approximate of the total insertion cost. 
We may decide to track these costs daily or weekly as part of our cost process.
Note also that if Google pricing for streaming inserts ever change, we would need to update our stats query to reflect that change.
This does not calculate pricing for queries on this …
=> calculate insertion costs on Client Side Applications Table

projects/client-side-events/datasets/Widget_Events/queries/TemplateUsageCompaniesPast30Days.bq, projects/client-side-events/datasets/Widget_Events/queries/TemplateUsageTotalCompaniesPast30Days.bq
TemplateUsageTotalCompaniesPast30Days.bq
- total count of unique companies that used templates in the past 30 days.
TemplateUsageCompaniesPast30Days.bq:
- list of companies ( id and name ) that used templates in the past 30 days, ordered by the number of displays owned by each one
=> query company template usage

projects/client-side-events/datasets/Installer_Events/views/PlayerModuleStats.bq
Only account for 'startup' events on Viewer_Events.events table when the actual viewer URL is loaded.
This query got outdated when we released no viewer mode.
=> Fix player module stats query

projects/Rise_Stats/datasets/customerData/views/companySnapshot.bq, projects/client-side-events/datasets/Uptime_Events/views/AverageUptimePct.bq, projects/client-side-events/datasets/Uptime_Events/views/DailyUptimePerDisplay.bq
companySnapshot was using the previously deleted obsolete view that didn't take whitescreen into account.
=> Refactor uptime for company snapshot compatability

projects/Rise_Stats/datasets/customerData/views/brandPromiseKPIs.bq
Brand promise should not count companies added as sub companies.
@sheadarlison @alanclayton FYI
=> Exclude sub companies from newSignups calculation

projects/client-side-events/datasets/ChromeOS_Player_Events/views/reliability.bq
- Theese errors were added to help investigate white screen events due to external content
=> Remove white screen check errors from ChrOS player reliabilitty

projects/client-side-events/datasets/Display_Events/CompaniesUsingHtmlTemplatesByDay.js
Currently we don't have data to validate this. I was also wondering if we should have a query that returns average usage per day for each template, but I guess that would be a separate card (if at all needed).
@santiagonoguez @stulees please review
=> Add query for Companies using a given Template per day

projects/client-side-events/datasets/Display_Events/DisplaysUsingHtmlTemplates.js
A simple additional filter to avoid empty names in the reports
=> filter out empty template names

projects/client-side-events/datasets/Display_Events/ComponentPresentationUsage.bq, projects/client-side-events/datasets/Display_Events/ComponentVersionStats.bq
- In order to release the overall fix for issue https://github.com/Rise-Vision/rise-vision-apps/issues/1063 , the _rise-image_ component must be released first and all displays must be using it before releasing Template Editor changes. To monitor how many displays are using latest release of a component, I've added _ComponentVersionStats.bq_.
- As a part of a Rollback plan also for issue 1063, it will be necessary to get a list of presentation ids (along with their respective company ids) that use the image component. This list will be used in collaboration with a list of companies that used Template Editor from FullStory. I've added _ComponentPresentationUsage.bq_ to get this presentation id list for a component. 
FYI, not adding the PR Template for this repo as it doesn't seem …
=> Helpful component/Template editor release queries

projects/client-side-events/datasets/Display_Events/ComponentReliabilityStable.bq
Adding this query to simplify the _components-widgets-config.js_ automated reliability script so it can run one query to extract and inject the reliability scores. Corresponding changes are in this [commit ](https://github.com/Rise-Vision/bq-sheet-insert/commit/ef4dd7b811a3244963ed28af14b3acb97f2a159e)
=> Adding unified stable component reliability view

projects/client-side-events/datasets/Apps_Events/views/SharedSchedulesStorageUsage.bq
A View to report daily Storage usage (bandwidth and #of request) from Shared Schedules.
As we don't have 'type=sharedschedule' requests yet, I tested with a different url parameter to validate the output.
=> Shared Schedules daily Storage Usage view

projects/client-side-events/datasets/Apps_Events/views/SharedSchedulesStorageUsage.bq
Update SharedSchedulesStorageUsage to standard SQL so that it can be used with Google Data Studio (it does not support legacy SQL).
Added the results to a sample Data Studio report.
=> Update SharedSchedulesStorageUsage to standard SQL

projects/endpoint-event-logs/datasets/logs/dailyUsageSummary.sql
Remove unnecessary join conditions for daily usage summary. 
We don't need the viewer entries to have the exact same schedule etc, only the date and endpointId are important because all we need from Viewer are OS, browser and viewer versions and those don't change from schedule to schedule.
=> Remove unnecessary join conditions for daily usage summary

projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
This is a change to the endpoint cost calculation that includes extracting cost data from legacy storage requests (from GCS Usage Logs), see this [diagram](https://docs.google.com/document/d/1i5E5VGaybBVLTSZ3wiTXG04Zhw8ENhdG2QDNLQXDTRo/edit?usp=sharing) for details.
=> Added legacy costs calculation

projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql, projects/endpoint-event-logs/datasets/logs/urlDecode.sql
Extracted URLDECODE into a permanent function because BQ does not allow temporary functions in views.
=> URLDECODE as a permanent function
